spring:
  application:
    name: book-master
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    com:
      wordyarc:
        bookmaster: INFO